apiVersion : apps/v1
kind: Deployment
metadata:
  name: "azureattachresultdev-bbea"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "azureattachresultdev-bbea"
  template:
    metadata:
      labels:
        app: "azureattachresultdev-bbea"
    spec:
      containers:
        - name: "azureattachresultdev-bbea"
          image: "ignitedevacr.azurecr.io/azureattachresultdev"
          env:
          - name: AZURE_STORAGE_ACCOUNT
            valueFrom:
              secretKeyRef:
                name: azure-storage
                key: account-name
          - name: AZURE_STORAGE_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: azure-storage
                key: access-key
          ports:
          - containerPort: 80